# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1onDfHP7OlUyeD-4HIBVXrD3UzSIehLUm
"""

import pandas as pd
data = pd.read_csv("HousingDatasetprepared_scored.csv")

Y = data["price"]
independent_variables = data.columns
independent_variables = independent_variables.delete(0)
independent_variables = independent_variables.delete(1)
independent_variables = independent_variables.delete(10)

from statsmodels.stats.outliers_influence import variance_inflation_factor
X = data[independent_variables]

X = X[independent_variables]
X.columns

# model fitting and prediction
import statsmodels.api as sm
regression_model = sm.OLS(Y,X)
regression_model = regression_model.fit()

#regression_model.summary()

import sys
index_counter = 1
user_dict ={} 
for column in X.columns:
  #temp_val = int(input("Enter "+column+":"))
  temp_val = int(sys.argv[index_counter])
  index_counter = index_counter + 1
  user_dict[column] = temp_val
user_input = pd.DataFrame(data = user_dict ,index = [0])
price = regression_model.predict(user_input)
print(round(price[0]))

